swagger: "2.0"
info:
  description: "Identificar si un ADN (array de caracteres) pertenece o no a un mutante. Se sabe que es mutante si se encuentra una secuencia de cuatro caracteres iguales de manera en horizontal, vertical u oblicua. Los caracteres permitidos en un ADN son: A, T, C, G."
  version: "1.0.0"
  title: "Prueba Mercado Libre"
host: "6d4611tose.execute-api.us-east-1.amazonaws.com"
basePath: ""
schemes:
  - "https"
paths:
  /mutant:
    post:
      tags:
        - "Mutant"
      summary: "validate DNA"
      description: ""
      operationId: "addMutant"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Adn object that needs to be added"
          required: true
          schema:
            $ref: "#/definitions/Mutant"
      responses:
        "200":
          description: "Is a mutant"
        "400":
          description: "Bad request"
        "403":
          description: "Is not a mutant"
        "500":
          description: "Internal serve error"
definitions:
  Mutant:
    type: "object"
    required:
      - "dna"
    properties:
      dna:
        type: "array"
        items:
          type: "string"
        example: ["CTGCGA","GGGGGG","TAAAGA","AAAAGG","CTTAGA","TCAGTA"]
    xml:
      name: "Mutant"